### ISSUE TITLE
Consider getting rid of .collection files

### ISSUE THREAD

**Issue by madeofpeople** [RobLoach/metalsmith-collections-convention#1]
Instead of defining conventions in a specific file, could we maybe just define collections by their presence in the yaml frontmatter of each file.

**Comment by RobLoach** [comment]
So something like the following?

#### `src/article/hello.md`
---
collection: articles
---
# Hello
```

**Comment by madeofpeople** [comment]
:+1: 
Aye, although maybe we're describing that whole dynamic collections pull request branch...

**Comment by RobLoach** [comment]
Added ability to add configuration from the metadata in the collection object:
https://github.com/RobLoach/metalsmith-collections-convention#metadata

**Comment by madeofpeople** [comment]
Now to rename the plugin… ;)

**Comment by RobLoach** [comment]
`metalsmith-collections-not-so-dynamic`
